version: "3.8"

services:
  postgres:
    container_name: blog_app_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres              # Default PostgreSQL user
      POSTGRES_PASSWORD: postgres          # Default PostgreSQL password
      PGDATA: /var/lib/postgresql/data     # Default PostgreSQL data directory
      POSTGRES_DB: blog_app_db             # Default database name
    volumes:
      - postgres_data:/var/lib/postgresql/data   # Mount a volume for persistence
    ports:
      - "5432:5432"                             # Expose PostgreSQL on default port 5432
    networks:
      - blog-app-network
    restart: unless-stopped

networks:
  blog-app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
